paths:
#api products
  /api/products:

#Get

    get:
      summary: Get all products.
      tags:
        - Products
      responses:
        "200":
          description: All products obtained.
          content:
            application/json:
              schema:
                type: array
                description: Array containing all products.
                items:
                  type: object
                  description: Product.
                  $ref: '#schemas/product'
              example:
                  - _id: ObjectId('64f4c4f4cf8d6dc14b9707d0')
                    title: Vaso Unicornio
                    category: Vasos
                    description: Vaso con tapa Unicornio, de 450 ml con sorbete.
                    price: 5000
                    thumbnail:
                    code: Vaso
                    stock: 50
                    owner: olivia113@gmail.com
                  - _id: ObjectId('64f4f0cc9797cb8f930d2f43')
                    title: Botella termica Floreada
                    category: Botellas
                    description: Botella termica, frio/calor, hasta 8 hrs mantiene la temperatura.
                    price: 10500
                    thumbnail: 
                    code: Botella
                    stock: 50
                    owner: aresden113@gmial.com
        "500":
          description: Server error.

#Post

    post:
      summary: Create a new product
      tags:
        - Products
      responses:
        "200":
          description: Product created succesfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message, with info about operation.
                  payload:
                    description: The created product.
                    $ref: '#schemas/Product' 
              example:
                message: Product updated.
                payload:
                    _id: ObjectId('64f4c4f4cf8d6dc14b9707d0')
                    title: Vaso Unicornio
                    category: Vasos
                    description: Vaso con tapa Unicornio, de 450 ml con sorbete.
                    price: 5000
                    thumbnail:
                    code: Vaso
                    stock: 50
                    owner: olivia113@gmail.com     
        "500":
          description: Server error.

#/api/products/{ProductId}

  /api/products/{ProductId}:

#Get

    get:
      summary: Get the product with named id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: This is the id of the product you want to get.
          schema:
            $type: String
      responses:
        "200":
          description: Product obtained.
          content:
            application/json:
              schema:
                $ref: '#schemas/Product'
        "404":
          description: The product was not found.
        "500":
          description: Server error.

#Put

    put:
      summary: Update the product with named id.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: This is the id of the product you want to update.
          schema:
            $type: String
      responses:
        "200":
          description: Product updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message, with info about operation.
                  payload:
                    description: The updated product.
                    $ref: '#schemas/Product' 
              example:
                message: Product updated.
                payload:
                    _id: ObjectId('64f4c4f4cf8d6dc14b9707d0')
                    title: Vaso Unicornio
                    category: Vasos
                    description: Vaso con tapa Unicornio, de 450 ml con sorbete.
                    price: 5000
                    thumbnail:
                    code: Vaso
                    stock: 50
                    owner: olivia113@gmail.com
        "404":
          description: The product was not found.
        "500":
          description: Server error.

#Delete

    delete:
      summary: Delete the product with named id.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: This is the id of the product you want to delete.
          schema:
            $type: String
      responses:
        "200":
          description: Product deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message, with info about operation.
                  payload:
                    description: The deleted product.
                    $ref: '#schemas/Product' 
              example:
                message: Product deleted.
                payload:
                    _id: ObjectId('64f4c4f4cf8d6dc14b9707d0')
                    title: Vaso Unicornio
                    category: Vasos
                    description: Vaso con tapa Unicornio, de 450 ml con sorbete.
                    price: 5000
                    thumbnail:
                    code: Vaso
                    stock: 50
                    owner: olivia113@gmail.com
        "404":
          description: The product was not found.
        "500":
          description: Server error.

#Products

    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Mongo document Id.
        title:
          type: String
          required: true
          description: Title of the product.
        category:
          type: String
          required: true
          description: Category of the product.
        description:
          type: String
          required: true
          description: Description of the product.
        price:
          type: Number
          required: true
          description: Price of the product.
        code:
          type: String
          required: true
          description: Unique code of the product.
        stock:
          type: Number
          required: true
          description: Stock of the product.
        owner:
          type: String
          required: true
          description: If premium user, then email. If admin, admin.

#Products Example

      example:
        _id: ObjectId('64f4c4f4cf8d6dc14b9707d0')
        title: Vaso Unicornio
        category: Vasos
        description: Vaso con tapa Unicornio, de 450 ml con sorbete.
        price: 5000
        thumbnail:
        code: Vaso
        stock: 50
        owner: olivia113@gmail.com